# Define the papers table.

import uuid 
from datetime import datetime, timezone 
from sqlalchemy import JSON, Boolean, Column, DateTime, String, Text
from sqlalchemy.dialects.postgresql import UUID 
from src.db.interfaces.postgresql import Base # # Base class for SQLAlchemy models. means it will be used to define the structure of the database tables and their relationships.


class Paper(Base):
    __tablename__ = "papers" # Define the name of the table in the database.

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4) # Define the id column as a UUID primary key with a default value generated by uuid.uuid4().
    arxiv_id = Column(String, unique= True, nullable = False, index = True)
    title = Column(String, nullable = False)
    authors = Column(JSON, nullable = False) # Store authors as a JSON array of strings.
    abstract = Column(Text, nullable = False) # Store the abstract as a text column.
    categories = Column(JSON, nullable=False)
    published_date = Column(DateTime(timezone=True), nullable=False) # Store the published date as a timezone-aware datetime.
    pdf_url = Column(String, nullable =False)
    created_at = Column(DateTime,default = lambda: datetime.now(timezone.utc) )
    updated_at = Column(DateTime, default = lambda: datetime.now(timezone.utc), onupdate = lambda: datetime.now(timezone.utc)) # Automatically update the updated_at column to the current UTC time whenever the row is updated.


    # parsed Pdf Content 
    raw_text = Column(Text, nullable=True) # Store the full raw text extracted from the PDF.
    sections = Column("section", JSON, nullable=True) # Store sections as a JSON array of objects with titles and content.
    references = Column(JSON, nullable=True) # Store references as a JSON array of objects if extracted.
    
    # PDF processing metadata
    parser_used = Column(String, nullable=True)
    parser_metadata = Column(JSON, nullable=True)
    pdf_processed = Column(Boolean, default=False, nullable=False)
    pdf_processing_date = Column(DateTime, nullable=True)